# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('product_type', models.CharField(choices=[('one_time', 'Разовая покупка'), ('subscription', 'Подписка')], default='one_time', max_length=20)),
                ('subscription_period', models.CharField(blank=True, help_text='monthly, yearly', max_length=20, null=True)),
                ('admin_url', models.URLField(blank=True, help_text='Ссылка на админ-панель продукта (общий для всех пользователей)', max_length=500, null=True, verbose_name='URL админки')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истек'), ('pending', 'Ожидает'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('app_url', models.URLField(blank=True, help_text='Ссылка на приложение (Mini App) для данного пользователя. Если не указана, можно задать в админке.', max_length=500, null=True, verbose_name='URL приложения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_method', models.ForeignKey(blank=True, help_text='Платежный метод для автоматического списания подписки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_products', to='payments.paymentmethod')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to='products.product')),
            ],
            options={
                'verbose_name': 'Продукт пользователя',
                'verbose_name_plural': 'Продукты пользователей',
                'db_table': 'user_products',
                'ordering': ['-created_at'],
            },
        ),
    ]
