# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='subscription_terms',
            field=models.ForeignKey(blank=True, help_text='Условия подписки для данного продукта (если продукт является подпиской)', limit_choices_to={'document_type': 'subscription_terms', 'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='documents.document'),
        ),
        migrations.AlterUniqueTogether(
            name='userproduct',
            unique_together={('user', 'product', 'status')},
        ),
    ]
