# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Одобрено (подписка отменена)'), ('rejected', 'Отклонено (подписка сохранена)'), ('expired', 'Истекло (автоматически отменено)')], default='pending', max_length=20, verbose_name='Статус')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('decision_comment', models.TextField(blank=True, verbose_name='Комментарий к решению')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('referrer_notified', models.BooleanField(default=False, verbose_name='Реферал уведомлен')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Напоминание отправлено')),
            ],
            options={
                'verbose_name': 'Запрос на отмену подписки',
                'verbose_name_plural': 'Запросы на отмену подписок',
                'db_table': 'cancellation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('rko', 'РКО')], default='rko', max_length=20)),
                ('bank', models.CharField(default='tinkoff', max_length=50)),
                ('mandate_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('revoked', 'Отозван'), ('expired', 'Истек')], default='active', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Мандат',
                'verbose_name_plural': 'Мандаты',
                'db_table': 'mandates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('reason', models.TextField()),
                ('channel', models.CharField(choices=[('tinkoff_mit', 'T-Bank MIT'), ('tinkoff_rko', 'T-Bank РКО')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('success', 'Успешно'), ('failed', 'Неудачно'), ('cancelled', 'Отменен')], default='pending', max_length=20)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ручное списание',
                'verbose_name_plural': 'Ручные списания',
                'db_table': 'manual_charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('success', 'Успешно'), ('failed', 'Неудачно'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', max_length=20)),
                ('method', models.CharField(choices=[('card', 'Карта'), ('mit', 'MIT'), ('rko', 'РКО')], default='card', max_length=20)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='tbank', max_length=50)),
                ('rebill_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('pan_mask', models.CharField(max_length=20)),
                ('exp_date', models.CharField(blank=True, max_length=10, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('revoked', 'Отозвана')], default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Платежный метод',
                'verbose_name_plural': 'Платежные методы',
                'db_table': 'payment_methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('payment', 'Платеж'), ('charge', 'Списание'), ('refund', 'Возврат'), ('manual_charge', 'Ручное списание')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manual_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.manualcharge')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
