# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualcharge',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manualcharge',
            name='mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_charges', to='payments.mandate'),
        ),
        migrations.AddField(
            model_name='manualcharge',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_charges', to='payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='manualcharge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_charges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mandate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Кто принял решение'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Реферал (принимает решение)'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_cancellation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='cancellationrequest',
            name='user_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_requests', to='products.userproduct', verbose_name='Подписка пользователя'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['provider_ref'], name='transaction_provide_fe9252_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-created_at'], name='transaction_created_cf5536_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_status_d621e5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payments_method_aea958_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider_ref'], name='payments_provide_788e74_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='payments_created_26b056_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcharge',
            index=models.Index(fields=['status'], name='manual_char_status_c6d567_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcharge',
            index=models.Index(fields=['channel'], name='manual_char_channel_86f20d_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcharge',
            index=models.Index(fields=['provider_ref'], name='manual_char_provide_b3dfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='manualcharge',
            index=models.Index(fields=['-created_at'], name='manual_char_created_aec525_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellationrequest',
            index=models.Index(fields=['status', 'expires_at'], name='cancellatio_status_19a4df_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellationrequest',
            index=models.Index(fields=['referrer', 'status'], name='cancellatio_referre_fbbb76_idx'),
        ),
        migrations.AddIndex(
            model_name='cancellationrequest',
            index=models.Index(fields=['requested_by'], name='cancellatio_request_752117_idx'),
        ),
    ]
