# Generated by Django 4.2.16 on 2025-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="purpose",
            field=models.CharField(
                blank=True,
                help_text="Например: card_binding, purchase",
                max_length=50,
                null=True,
            ),
        ),
    ]
