# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('FORM_SHOWED', 'Форма показана'), ('DEADLINE_EXPIRED', 'Срок истек'), ('CANCELED', 'Отменен'), ('PREAUTHORIZING', 'Предавторизация'), ('AUTHORIZING', 'Авторизация'), ('AUTHORIZED', 'Авторизован'), ('AUTH_FAIL', 'Ошибка авторизации'), ('REJECTED', 'Отклонен'), ('3DS_CHECKING', '3DS проверка'), ('3DS_CHECKED', '3DS проверен'), ('REVERSING', 'Возврат'), ('PARTIAL_REVERSED', 'Частичный возврат'), ('REVERSED', 'Возвращен'), ('CONFIRMED', 'Подтвержден'), ('REFUNDING', 'Возврат средств'), ('PARTIAL_REFUNDED', 'Частичный возврат'), ('REFUNDED', 'Возвращен')], default='NEW', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_url', models.URLField(blank=True, null=True)),
                ('subscription_agreed', models.BooleanField(default=False)),
                ('subscription_agreed_at', models.DateTimeField(blank=True, null=True)),
                ('referral_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('referral_code', models.CharField(blank=True, db_index=True, help_text='Реферальный код партнера', max_length=50, null=True)),
                ('expires_at', models.DateTimeField(help_text='Время истечения предзаказа')),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
                'db_table': 'pre_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
