# Generated by Django 4.2.16 on 2025-11-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_card_binding",
            field=models.BooleanField(
                default=False,
                help_text="Флаг, что заказ используется для привязки карты",
            ),
        ),
    ]
