# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=255)),
                ('action', models.CharField(max_length=100)),
                ('actor_email', models.EmailField(db_index=True, max_length=254)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('before', models.JSONField(blank=True, default=dict, null=True)),
                ('after', models.JSONField(blank=True, default=dict, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Журнал аудита',
                'verbose_name_plural': 'Журналы аудита',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
