# Generated by Django 4.2.16 on 2025-12-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_trackingevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trackingevent',
            new_name='tracking_ev_event_f6abee_idx',
            old_name='tracking_e_event_d18da2_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingevent',
            new_name='tracking_ev_session_958058_idx',
            old_name='tracking_e_session_fb11cf_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingevent',
            new_name='tracking_ev_user_id_13c859_idx',
            old_name='tracking_e_user_id_93af4e_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingevent',
            new_name='tracking_ev_cart_id_ab2223_idx',
            old_name='tracking_e_cart_id_aaed96_idx',
        ),
        migrations.RenameIndex(
            model_name='trackingevent',
            new_name='tracking_ev_created_48dd54_idx',
            old_name='tracking_e_created_8f1307_idx',
        ),
    ]
