# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('privacy', 'Политика конфиденциальности'), ('affiliate_terms', 'Условия партнерской программы'), ('cabinet_terms', 'Условия использования личного кабинета'), ('subscription_terms', 'Условия подписки'), ('other', 'Другое')], max_length=50, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание (HTML)')),
                ('content_text', models.TextField(blank=True, verbose_name='Содержание (текст)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='Meta title')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('version', models.IntegerField(default=1, verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(verbose_name='Версия документа')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Подписан')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='documents.document')),
            ],
            options={
                'verbose_name': 'Подписанный документ',
                'verbose_name_plural': 'Подписанные документы',
                'db_table': 'document_acceptances',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
