# Generated by Django 4.2.16 on 2025-11-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentacceptance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_acceptances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type', 'is_active', 'is_published'], name='documents_documen_902936_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['slug'], name='documents_slug_6a0040_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptance',
            index=models.Index(fields=['user', 'document'], name='document_ac_user_id_6225c0_idx'),
        ),
        migrations.AddIndex(
            model_name='documentacceptance',
            index=models.Index(fields=['-accepted_at'], name='document_ac_accepte_858785_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentacceptance',
            unique_together={('user', 'document', 'version')},
        ),
    ]
